---
name: Reusable Dependabot Auto Merge

on:
  workflow_call:

jobs:
  enable-automerge:
    name: Enable auto-merge
    runs-on: ubuntu-latest
    if: >-
      github.event.pull_request.head.repo.full_name == github.repository &&
      (
        github.event.pull_request.user.login == 'dependabot[bot]' ||
        github.event.pull_request.user.login == 'meyerstk[bot]'
      )

    steps:
      - name: Generate app token
        id: app-token
        uses: actions/create-github-app-token@v3
        with:
          client-id: ${{ vars.APP_CLIENT_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Enable auto-merge
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
          PR_URL: ${{ github.event.pull_request.html_url }}
